# Generated by Django 5.2.4 on 2025-08-03 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('slug', models.SlugField(editable=False, max_length=255)),
                ('doc', models.CharField(max_length=20, unique=True, verbose_name='Documento')),
                ('tipo_doc', models.CharField(choices=[('CPF', 'CPF'), ('CNPJ', 'CNPJ'), ('Passaporte', 'Passaporte')], max_length=20, verbose_name='Tipo de Documento')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('endereco', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço')),
                ('numero', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado')),
                ('pais', models.CharField(blank=True, max_length=100, null=True, verbose_name='País')),
                ('cep', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='pessoas/fotos/', verbose_name='Foto')),
                ('passaporte_numero', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número do Passaporte')),
                ('passaporte_validade', models.DateField(blank=True, null=True, verbose_name='Validade do Passaporte')),
                ('passaporte_copia', models.FileField(blank=True, null=True, upload_to='pessoas/passaportes/', verbose_name='Cópia do Passaporte')),
                ('passaporte_nome', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome no Passaporte')),
                ('nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('sexo', models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], max_length=10, null=True, verbose_name='Sexo')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Nome de usuário')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Equipe')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Data de cadastro')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.pessoa', verbose_name='Pessoa')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
    ]
