# Generated by Django 5.2.4 on 2025-08-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='empresa_gruporom',
            field=models.BooleanField(default=False, verbose_name='Empresa do Grupo ROM'),
        ),
    ]
