# Generated by Django 5.2.4 on 2025-08-04 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pessoa_empresa_gruporom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_empresa', models.CharField(choices=[('Alimentação', 'Alimentação'), ('Turismo', 'Turismo'), ('Administração de Bens', 'Administração de Bens')], max_length=50, verbose_name='Tipo de Empresa')),
                ('empresas', models.ManyToManyField(limit_choices_to={'empresa_gruporom': True}, related_name='fornecedores_relacionados', to='core.pessoa', verbose_name='Empresas do Grupo ROM')),
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fornecedor', to='core.pessoa', verbose_name='Pessoa')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['pessoa__nome'],
            },
        ),
    ]
