# Generated by Django 5.2.4 on 2025-08-04 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_fornecedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='pessoa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='fornecedor', to='core.pessoa', verbose_name='Pessoa'),
        ),
    ]
