# Generated by Django 5.2.4 on 2025-08-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_fornecedor_pessoa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(help_text='Data da cotação do câmbio', unique=True, verbose_name='Data')),
                ('valor', models.DecimalField(decimal_places=4, help_text='Cotação do dólar em reais (ex: 5.2345)', max_digits=10, verbose_name='Valor do Dólar')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Câmbio',
                'verbose_name_plural': 'Câmbios',
                'ordering': ['-data'],
            },
        ),
    ]
