# Generated by Django 5.2.4 on 2025-08-04 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_cambio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Diretor Executivo, Gerente de Vendas, Analista de Marketing', max_length=100, verbose_name='Nome do Cargo')),
                ('ativo', models.BooleanField(default=True, help_text='Cargos inativos não aparecem em novas seleções', verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('empresa', models.ForeignKey(help_text='Empresa do Grupo ROM onde o cargo existe', limit_choices_to={'empresa_gruporom': True}, on_delete=django.db.models.deletion.PROTECT, related_name='cargos', to='core.pessoa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'ordering': ['empresa', 'nome'],
                'unique_together': {('nome', 'empresa')},
            },
        ),
    ]
