# Generated by Django 5.2.4 on 2025-08-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_cargo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Manhã, Tarde, Noite, Madrugada', max_length=50, unique=True, verbose_name='Nome do Turno')),
                ('inicio', models.TimeField(help_text='Horário de início do turno (ex: 08:00)', verbose_name='Horário de Início')),
                ('fim', models.TimeField(help_text='Horário de fim do turno (ex: 17:00)', verbose_name='Horário de Fim')),
                ('ativo', models.BooleanField(default=True, help_text='Turnos inativos não aparecem em novas seleções', verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['inicio'],
            },
        ),
    ]
