# Generated by Django 5.2.4 on 2025-08-04 17:14

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_turno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario', models.DecimalField(decimal_places=2, help_text='Salário base do colaborador', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Salário')),
                ('data_admissao', models.DateField(verbose_name='Data de Admissão')),
                ('data_demissao', models.DateField(blank=True, null=True, verbose_name='Data de Demissão')),
                ('gorjeta', models.BooleanField(default=False, help_text='Indica se o colaborador recebe gorjetas', verbose_name='Recebe Gorjeta')),
                ('comissao', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentual de comissão sobre vendas', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Comissão (%)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='colaboradores', to='core.cargo', verbose_name='Cargo')),
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='colaborador', to='core.pessoa', verbose_name='Pessoa')),
                ('turnos', models.ManyToManyField(blank=True, help_text='Turnos que o colaborador pode trabalhar', related_name='colaboradores', to='core.turno', verbose_name='Turnos')),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
                'ordering': ['pessoa__nome'],
            },
        ),
    ]
