# Generated by Django 5.2.4 on 2025-08-05 15:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_colaborador"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nome identificador da conta WhatsApp Business",
                        max_length=100,
                        verbose_name="Nome da Conta",
                    ),
                ),
                (
                    "phone_number_id",
                    models.CharField(
                        help_text="ID do número de telefone na API do WhatsApp",
                        max_length=50,
                        unique=True,
                        verbose_name="Phone Number ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        help_text="Número no formato internacional",
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Número deve estar no formato internacional (+5511999999999)",
                                regex="^\\+[1-9]\\d{1,14}$",
                            )
                        ],
                        verbose_name="Número de Telefone",
                    ),
                ),
                (
                    "access_token",
                    models.TextField(
                        help_text="Token de acesso permanente para a API",
                        verbose_name="Token de Acesso",
                    ),
                ),
                (
                    "webhook_verify_token",
                    models.CharField(
                        help_text="Token para verificação do webhook",
                        max_length=255,
                        verbose_name="Token de Verificação Webhook",
                    ),
                ),
                (
                    "business_account_id",
                    models.CharField(
                        help_text="ID da conta de negócios do WhatsApp",
                        max_length=50,
                        verbose_name="Business Account ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("active", "Ativo"),
                            ("suspended", "Suspenso"),
                            ("disabled", "Desabilitado"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "responsavel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="whatsapp_accounts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsável",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conta WhatsApp",
                "verbose_name_plural": "Contas WhatsApp",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WhatsAppContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Número deve estar no formato internacional (+5511999999999)",
                                regex="^\\+[1-9]\\d{1,14}$",
                            )
                        ],
                        verbose_name="Número de Telefone",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Nome do contato no WhatsApp",
                        max_length=200,
                        verbose_name="Nome",
                    ),
                ),
                (
                    "profile_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Nome do Perfil"
                    ),
                ),
                (
                    "is_business",
                    models.BooleanField(default=False, verbose_name="É Empresa"),
                ),
                (
                    "last_seen",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Última Visualização"
                    ),
                ),
                (
                    "is_blocked",
                    models.BooleanField(default=False, verbose_name="Bloqueado"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="core.whatsappaccount",
                        verbose_name="Conta WhatsApp",
                    ),
                ),
                (
                    "pessoa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="whatsapp_contacts",
                        to="core.pessoa",
                        verbose_name="Pessoa Relacionada",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contato WhatsApp",
                "verbose_name_plural": "Contatos WhatsApp",
                "ordering": ["name", "phone_number"],
                "unique_together": {("account", "phone_number")},
            },
        ),
        migrations.CreateModel(
            name="WhatsAppMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wamid",
                    models.CharField(
                        help_text="ID único da mensagem no WhatsApp",
                        max_length=100,
                        unique=True,
                        verbose_name="WhatsApp Message ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("inbound", "Recebida"), ("outbound", "Enviada")],
                        max_length=10,
                        verbose_name="Direção",
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "Texto"),
                            ("image", "Imagem"),
                            ("document", "Documento"),
                            ("audio", "Áudio"),
                            ("video", "Vídeo"),
                            ("sticker", "Figurinha"),
                            ("location", "Localização"),
                            ("contacts", "Contatos"),
                            ("template", "Template"),
                            ("interactive", "Interativo"),
                            ("system", "Sistema"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="Texto da mensagem ou dados JSON para outros tipos",
                        verbose_name="Conteúdo",
                    ),
                ),
                (
                    "media_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ID da Mídia"
                    ),
                ),
                ("media_url", models.URLField(blank=True, verbose_name="URL da Mídia")),
                (
                    "media_filename",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Nome do Arquivo"
                    ),
                ),
                (
                    "media_mimetype",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Tipo MIME"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "Enviada"),
                            ("delivered", "Entregue"),
                            ("read", "Lida"),
                            ("failed", "Falhou"),
                            ("pending", "Pendente"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        help_text="Timestamp original do WhatsApp",
                        verbose_name="Timestamp da Mensagem",
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Entregue em"
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Lida em"),
                ),
                (
                    "context_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Dados adicionais da mensagem (buttons, lists, etc.)",
                        verbose_name="Dados de Contexto",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Mensagem de Erro"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="core.whatsappaccount",
                        verbose_name="Conta WhatsApp",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="core.whatsappcontact",
                        verbose_name="Contato",
                    ),
                ),
                (
                    "reply_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replies",
                        to="core.whatsappmessage",
                        verbose_name="Resposta para",
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="whatsapp_messages_sent",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Enviada por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensagem WhatsApp",
                "verbose_name_plural": "Mensagens WhatsApp",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["account", "contact", "-timestamp"],
                        name="core_whatsa_account_b410f6_idx",
                    ),
                    models.Index(
                        fields=["direction", "-timestamp"],
                        name="core_whatsa_directi_253d29_idx",
                    ),
                    models.Index(
                        fields=["status", "-timestamp"],
                        name="core_whatsa_status_ff3f4c_idx",
                    ),
                ],
            },
        ),
    ]
