# Generated by Django 5.2.4 on 2025-08-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_whatsappaccount_whatsappcontact_whatsappmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="whatsappaccount",
            name="app_id",
            field=models.CharField(
                blank=True,
                help_text="App ID obtido no Facebook for Developers",
                max_length=50,
                verbose_name="ID do Aplicativo",
            ),
        ),
        migrations.AddField(
            model_name="whatsappaccount",
            name="app_secret",
            field=models.CharField(
                blank=True,
                help_text="App Secret obtido no Facebook for Developers",
                max_length=255,
                verbose_name="Chave Secreta do Aplicativo",
            ),
        ),
    ]
