# Generated by Django 5.2.4 on 2025-08-05 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_whatsappaccount_app_id_whatsappaccount_app_secret"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nome único do template (apenas letras minúsculas, números e _)",
                        max_length=512,
                        verbose_name="Nome do Template",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Nome amigável para exibição na interface",
                        max_length=255,
                        verbose_name="Nome de Exibição",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("marketing", "Marketing"),
                            ("utility", "Utilidade"),
                            ("authentication", "Autenticação"),
                        ],
                        max_length=20,
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("pt_BR", "Português (Brasil)"),
                            ("en_US", "Inglês (EUA)"),
                            ("es_ES", "Espanhol"),
                            ("en", "Inglês"),
                            ("pt", "Português"),
                        ],
                        default="pt_BR",
                        max_length=10,
                        verbose_name="Idioma",
                    ),
                ),
                (
                    "header_text",
                    models.TextField(
                        blank=True,
                        help_text="Texto do cabeçalho (máximo 60 caracteres)",
                        max_length=60,
                        verbose_name="Cabeçalho",
                    ),
                ),
                (
                    "body_text",
                    models.TextField(
                        help_text="Texto principal do template. Use {{1}}, {{2}} para variáveis",
                        max_length=1024,
                        verbose_name="Corpo da Mensagem",
                    ),
                ),
                (
                    "footer_text",
                    models.CharField(
                        blank=True,
                        help_text="Texto do rodapé (máximo 60 caracteres)",
                        max_length=60,
                        verbose_name="Rodapé",
                    ),
                ),
                (
                    "template_id",
                    models.CharField(
                        blank=True,
                        help_text="ID retornado pela API do WhatsApp",
                        max_length=100,
                        verbose_name="ID do Template",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("approved", "Aprovado"),
                            ("rejected", "Rejeitado"),
                            ("disabled", "Desabilitado"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True,
                        help_text="Motivo da rejeição retornado pela API",
                        verbose_name="Motivo da Rejeição",
                    ),
                ),
                (
                    "has_buttons",
                    models.BooleanField(default=False, verbose_name="Tem Botões"),
                ),
                (
                    "buttons_config",
                    models.JSONField(
                        blank=True,
                        help_text="JSON com configuração dos botões",
                        null=True,
                        verbose_name="Configuração dos Botões",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="templates",
                        to="core.whatsappaccount",
                        verbose_name="Conta WhatsApp",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="whatsapp_templates_criados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Template WhatsApp",
                "verbose_name_plural": "Templates WhatsApp",
                "db_table": "whatsapp_template",
                "ordering": ["-criado_em"],
                "unique_together": {("account", "name", "language")},
            },
        ),
    ]
