# Generated by Django 5.2.4 on 2025-08-05 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_whatsapptemplate"),
    ]

    operations = [
        migrations.AddField(
            model_name="whatsapptemplate",
            name="variables_examples",
            field=models.JSONField(
                blank=True,
                help_text="Exemplos das variáveis {{1}}, {{2}}, etc. para envio à API",
                null=True,
                verbose_name="Exemplos de Variáveis",
            ),
        ),
    ]
