# Generated by Django 5.2.4 on 2025-08-06 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_whatsapptemplate_variables_examples"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Aguardando Atendimento"),
                            ("assigned", "Atribuída"),
                            ("in_progress", "Em Atendimento"),
                            ("resolved", "Resolvida"),
                            ("closed", "Encerrada"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "first_message_at",
                    models.DateTimeField(verbose_name="Primeira mensagem em"),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Atribuída em"
                    ),
                ),
                (
                    "last_activity",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última atividade"
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Resolvida em"
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Baixa"),
                            ("medium", "Média"),
                            ("high", "Alta"),
                            ("urgent", "Urgente"),
                        ],
                        default="medium",
                        max_length=10,
                        verbose_name="Prioridade",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Tags para categorização",
                        verbose_name="Tags",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Notas internas sobre a conversa",
                        verbose_name="Notas",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to="core.whatsappaccount",
                        verbose_name="Conta WhatsApp",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="whatsapp_conversations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atendente",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to="core.whatsappcontact",
                        verbose_name="Contato",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conversa WhatsApp",
                "verbose_name_plural": "Conversas WhatsApp",
                "ordering": ["-last_activity"],
            },
        ),
        migrations.AddField(
            model_name="whatsappmessage",
            name="conversation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="core.whatsappconversation",
                verbose_name="Conversa",
            ),
        ),
        migrations.AddIndex(
            model_name="whatsappconversation",
            index=models.Index(
                fields=["status", "-last_activity"],
                name="core_whatsa_status_f8f935_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="whatsappconversation",
            index=models.Index(
                fields=["assigned_to", "-last_activity"],
                name="core_whatsa_assigne_85db65_idx",
            ),
        ),
    ]
