# Generated by Django 5.2.4 on 2025-08-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_whatsappconversation_whatsappmessage_conversation_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CiaArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=200, verbose_name="Nome da Companhia Aérea"
                    ),
                ),
                (
                    "iata",
                    models.CharField(
                        max_length=3, unique=True, verbose_name="Código IATA"
                    ),
                ),
            ],
            options={
                "verbose_name": "Companhia Aérea",
                "verbose_name_plural": "Companhias Aéreas",
                "ordering": ["nome"],
            },
        ),
    ]
