# Generated by Django 5.2.4 on 2025-08-07 15:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_ciaarea"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=100, verbose_name="Nome da Cidade"),
                ),
            ],
            options={
                "verbose_name": "Cidade",
                "verbose_name_plural": "Cidades",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Incluso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=200, verbose_name="Descrição"),
                ),
                ("incluso", models.BooleanField(verbose_name="Incluso")),
                ("padrao", models.BooleanField(default=False, verbose_name="Padrão")),
            ],
            options={
                "verbose_name": "Item Incluso",
                "verbose_name_plural": "Itens Inclusos",
                "ordering": ["-incluso", "descricao"],
            },
        ),
        migrations.CreateModel(
            name="Pais",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Nome do País")),
                (
                    "iso",
                    models.CharField(
                        max_length=2, unique=True, verbose_name="Código ISO"
                    ),
                ),
            ],
            options={
                "verbose_name": "País",
                "verbose_name_plural": "Países",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Caravana",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=200, verbose_name="Nome da Caravana"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("Evangélica", "Evangélica"),
                            ("Católica", "Católica"),
                            ("Lazer", "Lazer"),
                            ("Mentoria", "Mentoria"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                ("link", models.URLField(blank=True, null=True, verbose_name="Link")),
                (
                    "destaque_site",
                    models.IntegerField(default=0, verbose_name="Destaque no Site"),
                ),
                (
                    "repasse_valor",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor do Repasse"
                    ),
                ),
                (
                    "repasse_tipo",
                    models.CharField(
                        choices=[
                            ("Total", "Total"),
                            ("Por Passageiro", "Por Passageiro"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Repasse",
                    ),
                ),
                (
                    "banner_site",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="caravanas/banners/",
                        verbose_name="Banner do Site",
                    ),
                ),
                (
                    "banner_mobile",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="caravanas/banners_mobile/",
                        verbose_name="Banner Mobile",
                    ),
                ),
                (
                    "quantidade",
                    models.PositiveIntegerField(
                        verbose_name="Quantidade de Passageiros"
                    ),
                ),
                (
                    "free_economica",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Free Econômica"
                    ),
                ),
                (
                    "free_executiva",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Free Executiva"
                    ),
                ),
                ("data_contrato", models.DateField(verbose_name="Data do Contrato")),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="caravanas_empresa",
                        to="core.pessoa",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "lideres",
                    models.ManyToManyField(
                        blank=True,
                        related_name="caravanas_lideres",
                        to="core.pessoa",
                        verbose_name="Líderes",
                    ),
                ),
                (
                    "promotor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="caravanas_promotor",
                        to="core.pessoa",
                        verbose_name="Promotor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Caravana",
                "verbose_name_plural": "Caravanas",
                "ordering": ["-data_contrato", "nome"],
            },
        ),
        migrations.CreateModel(
            name="Bloqueio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=500, verbose_name="Descrição"),
                ),
                ("saida", models.DateField(verbose_name="Data de Saída")),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor"
                    ),
                ),
                (
                    "taxas",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Taxas"
                    ),
                ),
                (
                    "moeda_valor",
                    models.CharField(
                        choices=[("Dólar", "Dólar"), ("Real", "Real")],
                        max_length=10,
                        verbose_name="Moeda do Valor",
                    ),
                ),
                (
                    "moeda_taxas",
                    models.CharField(
                        choices=[("Dólar", "Dólar"), ("Real", "Real")],
                        max_length=10,
                        verbose_name="Moeda das Taxas",
                    ),
                ),
                (
                    "terrestre",
                    models.BooleanField(default=False, verbose_name="Terrestre"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "caravana",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.caravana",
                        verbose_name="Caravana",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bloqueio",
                "verbose_name_plural": "Bloqueios",
                "ordering": ["saida"],
            },
        ),
        migrations.CreateModel(
            name="Aeroporto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=200, verbose_name="Nome do Aeroporto"),
                ),
                (
                    "iata",
                    models.CharField(
                        max_length=3, unique=True, verbose_name="Código IATA"
                    ),
                ),
                (
                    "timezone",
                    models.CharField(max_length=50, verbose_name="Fuso Horário"),
                ),
                (
                    "cidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.cidade",
                        verbose_name="Cidade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aeroporto",
                "verbose_name_plural": "Aeroportos",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Extra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=200, verbose_name="Descrição"),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor"
                    ),
                ),
                (
                    "moeda",
                    models.CharField(
                        choices=[("Dólar", "Dólar"), ("Real", "Real")],
                        max_length=10,
                        verbose_name="Moeda",
                    ),
                ),
                (
                    "bloqueio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.bloqueio",
                        verbose_name="Bloqueio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Extra",
                "verbose_name_plural": "Extras",
                "ordering": ["descricao"],
            },
        ),
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=200, verbose_name="Nome do Hotel"),
                ),
                ("endereco", models.CharField(max_length=500, verbose_name="Endereço")),
                (
                    "telefone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Telefone"
                    ),
                ),
                (
                    "foto",
                    models.ImageField(
                        blank=True, null=True, upload_to="hoteis/", verbose_name="Foto"
                    ),
                ),
                (
                    "cidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.cidade",
                        verbose_name="Cidade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hotel",
                "verbose_name_plural": "Hotéis",
                "ordering": ["nome"],
            },
        ),
        migrations.AddField(
            model_name="bloqueio",
            name="hoteis",
            field=models.ManyToManyField(
                blank=True, to="core.hotel", verbose_name="Hotéis"
            ),
        ),
        migrations.AddField(
            model_name="bloqueio",
            name="inclusos",
            field=models.ManyToManyField(
                blank=True, to="core.incluso", verbose_name="Itens Inclusos"
            ),
        ),
        migrations.CreateModel(
            name="Nota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.TextField(verbose_name="Descrição")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Criada em"
                    ),
                ),
                (
                    "resposta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.nota",
                        verbose_name="Resposta para",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nota",
                "verbose_name_plural": "Notas",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="cidade",
            name="pais",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="core.pais",
                verbose_name="País",
            ),
        ),
        migrations.AddField(
            model_name="bloqueio",
            name="paises",
            field=models.ManyToManyField(
                blank=True, to="core.pais", verbose_name="Países"
            ),
        ),
        migrations.CreateModel(
            name="Tarefa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("Aéreo", "Aéreo"),
                            ("Terrestre", "Terrestre"),
                            ("Passageiro", "Passageiro"),
                        ],
                        max_length=20,
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=500, verbose_name="Descrição"),
                ),
                (
                    "concluida_em",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Concluída em"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Criada em"
                    ),
                ),
                (
                    "bloqueio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.bloqueio",
                        verbose_name="Bloqueio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarefa",
                "verbose_name_plural": "Tarefas",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Voo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(max_length=20, verbose_name="Número do Voo"),
                ),
                (
                    "embarque",
                    models.DateTimeField(verbose_name="Data/Hora de Embarque"),
                ),
                (
                    "desembarque",
                    models.DateTimeField(verbose_name="Data/Hora de Desembarque"),
                ),
                (
                    "aeroporto_desembarque",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="voos_desembarque",
                        to="core.aeroporto",
                        verbose_name="Aeroporto de Desembarque",
                    ),
                ),
                (
                    "aeroporto_embarque",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="voos_embarque",
                        to="core.aeroporto",
                        verbose_name="Aeroporto de Embarque",
                    ),
                ),
                (
                    "bloqueio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.bloqueio",
                        verbose_name="Bloqueio",
                    ),
                ),
                (
                    "cia_aerea",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.ciaarea",
                        verbose_name="Companhia Aérea",
                    ),
                ),
            ],
            options={
                "verbose_name": "Voo",
                "verbose_name_plural": "Voos",
                "ordering": ["embarque"],
            },
        ),
        migrations.CreateModel(
            name="DiaRoteiro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordem", models.PositiveIntegerField(verbose_name="Ordem")),
                ("titulo", models.CharField(max_length=200, verbose_name="Título")),
                ("descricao", models.TextField(verbose_name="Descrição")),
                (
                    "bloqueio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.bloqueio",
                        verbose_name="Bloqueio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dia do Roteiro",
                "verbose_name_plural": "Dias do Roteiro",
                "ordering": ["bloqueio", "ordem"],
                "unique_together": {("bloqueio", "ordem")},
            },
        ),
        migrations.CreateModel(
            name="Passageiro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        blank=True,
                        choices=[("Guia", "Guia"), ("VIP", "VIP"), ("Free", "Free")],
                        max_length=10,
                        null=True,
                        verbose_name="Tipo",
                    ),
                ),
                ("single", models.BooleanField(default=False, verbose_name="Single")),
                (
                    "bloqueio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.bloqueio",
                        verbose_name="Bloqueio",
                    ),
                ),
                (
                    "pessoa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.pessoa",
                        verbose_name="Pessoa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Passageiro",
                "verbose_name_plural": "Passageiros",
                "ordering": ["pessoa__nome"],
                "unique_together": {("pessoa", "bloqueio")},
            },
        ),
    ]
