# Generated by Django 5.2.4 on 2025-08-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_cidade_incluso_pais_caravana_bloqueio_aeroporto_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pessoa",
            name="tipo_empresa",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Alimentação", "Alimentação"),
                    ("Turismo", "Turismo"),
                    ("Administração de Bens", "Administração de Bens"),
                ],
                max_length=50,
                null=True,
                verbose_name="Tipo de Empresa",
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="empresas",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"empresa_gruporom": True},
                related_name="usuarios_empresa",
                to="core.pessoa",
                verbose_name="Empresas do Grupo ROM",
            ),
        ),
    ]
