# Generated by Django 5.2.4 on 2025-08-07 20:37

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_pessoa_tipo_empresa_usuario_empresas"),
    ]

    operations = [
        migrations.AlterField(
            model_name="whatsappaccount",
            name="access_token",
            field=core.fields.EncryptedTextField(
                help_text="Token de acesso permanente para a API",
                verbose_name="Token de Acesso",
            ),
        ),
        migrations.AlterField(
            model_name="whatsappaccount",
            name="app_secret",
            field=core.fields.EncryptedCharField(
                blank=True,
                help_text="App Secret obtido no Facebook for Developers",
                max_length=500,
                verbose_name="Chave Secreta do Aplicativo",
            ),
        ),
        migrations.AlterField(
            model_name="whatsappaccount",
            name="webhook_verify_token",
            field=core.fields.EncryptedCharField(
                help_text="Token para verificação do webhook",
                max_length=500,
                verbose_name="Token de Verificação Webhook",
            ),
        ),
    ]
