# Generated by Django 5.2.4 on 2025-08-07 22:22

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_alter_whatsappaccount_app_secret_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="whatsappaccount",
            name="app_secret",
            field=core.fields.EncryptedTextField(
                blank=True,
                help_text="App Secret obtido no Facebook for Developers",
                verbose_name="Chave Secreta do Aplicativo",
            ),
        ),
        migrations.AlterField(
            model_name="whatsappaccount",
            name="webhook_verify_token",
            field=core.fields.EncryptedTextField(
                help_text="Token para verificação do webhook",
                verbose_name="Token de Verificação Webhook",
            ),
        ),
    ]
