# Generated by Django

from django.db import migrations, models
import django.db.models.deletion


def set_default_responsavel(apps, schema_editor):
    """
    Define a primeira pessoa do sistema como responsável padrão
    para todas as caravanas existentes
    """
    Pessoa = apps.get_model('core', 'Pessoa')
    Caravana = apps.get_model('core', 'Caravana')
    
    # Buscar a primeira pessoa
    primeira_pessoa = Pessoa.objects.first()
    
    if primeira_pessoa:
        # Atualizar todas as caravanas existentes com a primeira pessoa como responsável
        Caravana.objects.filter(responsavel__isnull=True).update(responsavel=primeira_pessoa.id)


def reverse_default_responsavel(apps, schema_editor):
    """
    Operação reversa - remove o campo responsavel das caravanas
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_whatsappaccount_app_secret_and_more'),
    ]

    operations = [
        # Criar modelo Funcao
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masculino', models.CharField(max_length=100, verbose_name='Título Masculino')),
                ('feminino', models.CharField(max_length=100, verbose_name='Título Feminino')),
                ('abreviacao_masculino', models.CharField(max_length=20, verbose_name='Abrev. de Título Masculino')),
                ('abreviacao_feminino', models.CharField(max_length=20, verbose_name='Abrev. de Título Feminino')),
            ],
            options={
                'verbose_name': 'Função',
                'verbose_name_plural': 'Funções',
                'ordering': ['masculino'],
            },
        ),
        # Adicionar campo responsavel como nullable primeiro
        migrations.AddField(
            model_name='caravana',
            name='responsavel',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='caravanas_responsavel', to='core.pessoa', verbose_name='Responsável'),
        ),
        # Executar função Python para definir valores padrão
        migrations.RunPython(set_default_responsavel, reverse_default_responsavel),
        # Tornar campo obrigatório após definir valores
        migrations.AlterField(
            model_name='caravana',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='caravanas_responsavel', to='core.pessoa', verbose_name='Responsável'),
        ),
    ]