# Generated by Django 5.2.4 on 2025-08-08 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_funcao_caravana_responsavel"),
    ]

    operations = [
        migrations.AddField(
            model_name="pessoa",
            name="funcao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.funcao",
                verbose_name="Função",
            ),
        ),
    ]
