# Generated by Django 5.2.4 on 2025-08-08 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_add_funcao_to_pessoa"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppWebhookQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        help_text="Dados completos recebidos do webhook",
                        verbose_name="Payload do Webhook",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("processing", "Processando"),
                            ("processed", "Processado"),
                            ("failed", "Falhou"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "attempts",
                    models.IntegerField(
                        default=0, verbose_name="Tentativas de Processamento"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Mensagem de Erro"),
                ),
                (
                    "received_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Recebido em"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Processado em"
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_queue",
                        to="core.whatsappaccount",
                        verbose_name="Conta WhatsApp",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fila de Webhook",
                "verbose_name_plural": "Fila de Webhooks",
                "ordering": ["-received_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "received_at"],
                        name="core_whatsa_status_f79e99_idx",
                    ),
                    models.Index(
                        fields=["account", "status"],
                        name="core_whatsa_account_f434be_idx",
                    ),
                ],
            },
        ),
    ]
