# Generated by Django 5.2.4 on 2025-08-08 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_whatsapp_webhook_queue"),
    ]

    operations = [
        migrations.AlterField(
            model_name="whatsappmessage",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendente"),
                    ("sending", "Enviando"),
                    ("sent", "Enviada"),
                    ("delivered", "Entregue"),
                    ("read", "Lida"),
                    ("failed", "Falhou"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
