# Generated by Django 5.2.4 on 2025-08-09 00:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_add_sending_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pessoa",
            name="email",
        ),
        migrations.RemoveField(
            model_name="pessoa",
            name="telefone",
        ),
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="E-mail")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("pessoal", "Pessoal"),
                            ("profissional", "Profissional"),
                            ("comercial", "Comercial"),
                            ("outro", "Outro"),
                        ],
                        default="pessoal",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "principal",
                    models.BooleanField(default=False, verbose_name="Principal"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "verificado",
                    models.BooleanField(default=False, verbose_name="Verificado"),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "pessoa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emails",
                        to="core.pessoa",
                        verbose_name="Pessoa",
                    ),
                ),
            ],
            options={
                "verbose_name": "E-mail",
                "verbose_name_plural": "E-mails",
                "ordering": ["-principal", "-criado_em"],
                "indexes": [
                    models.Index(
                        fields=["pessoa", "principal"],
                        name="core_email_pessoa__fb1e81_idx",
                    ),
                    models.Index(fields=["email"], name="core_email_email_c5b753_idx"),
                ],
                "unique_together": {("pessoa", "email")},
            },
        ),
        migrations.CreateModel(
            name="Telefone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ddi",
                    models.CharField(
                        help_text="Código do país (ex: 55 para Brasil)",
                        max_length=4,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="DDI deve conter apenas números (1-4 dígitos)",
                                regex="^\\d{1,4}$",
                            )
                        ],
                        verbose_name="DDI",
                    ),
                ),
                (
                    "ddd",
                    models.CharField(
                        help_text="Código de área (ex: 11)",
                        max_length=3,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="DDD deve conter 2-3 números",
                                regex="^\\d{2,3}$",
                            )
                        ],
                        verbose_name="DDD",
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Telefone deve conter apenas números (7-15 dígitos)",
                                regex="^\\d{7,15}$",
                            )
                        ],
                        verbose_name="Telefone",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("celular", "Celular"),
                            ("residencial", "Residencial"),
                            ("comercial", "Comercial"),
                            ("whatsapp", "WhatsApp"),
                            ("outro", "Outro"),
                        ],
                        default="celular",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "principal",
                    models.BooleanField(default=False, verbose_name="Principal"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "pessoa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telefones",
                        to="core.pessoa",
                        verbose_name="Pessoa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Telefone",
                "verbose_name_plural": "Telefones",
                "ordering": ["-principal", "-criado_em"],
                "indexes": [
                    models.Index(
                        fields=["pessoa", "principal"],
                        name="core_telefo_pessoa__d4c7c4_idx",
                    ),
                    models.Index(
                        fields=["ddi", "ddd", "telefone"],
                        name="core_telefo_ddi_871876_idx",
                    ),
                ],
            },
        ),
    ]
