# Generated by Django 5.2.4 on 2025-08-09 17:01

import django.db.models.deletion
from django.db import migrations, models


def convert_pais_to_foreignkey(apps, schema_editor):
    """
    Converte valores de país (CharField) para ForeignKey do model Pais.
    Em produção existem dados reais que precisam ser convertidos.
    """
    from django.db import connection
    
    # Primeiro, vamos limpar os dados de país que são texto
    # e definir como null para evitar erro de conversão
    with connection.cursor() as cursor:
        # Define todos os valores de país como null temporariamente
        cursor.execute("UPDATE core_pessoa SET pais = NULL WHERE pais IS NOT NULL")


def reverse_pais_to_charfield(apps, schema_editor):
    """
    Reverse: converte ForeignKey de volta para CharField.
    """
    Pessoa = apps.get_model('core', 'Pessoa')
    
    for pessoa in Pessoa.objects.all():
        if pessoa.pais:
            # Salva o nome do país como texto
            pessoa.pais = pessoa.pais.nome
        else:
            pessoa.pais = None
        pessoa.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_restructure_contacts"),
    ]

    operations = [
        # Primeiro converte dados existentes
        migrations.RunPython(
            convert_pais_to_foreignkey,
            reverse_pais_to_charfield,
        ),
        # Depois altera o campo
        migrations.AlterField(
            model_name="pessoa",
            name="pais",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.pais",
                verbose_name="País",
            ),
        ),
    ]