# Generated by Django 5.2.4 on 2025-08-09 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_restructure_contacts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pessoa",
            name="pais",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.pais",
                verbose_name="País",
            ),
        ),
    ]
