# Generated by Django 5.2.4 on 2025-08-09 17:01

import django.db.models.deletion
from django.db import migrations, models


def clear_pais_data(apps, schema_editor):
    """
    Define todos os valores de país como NULL antes da conversão.
    """
    from django.db import connection
    with connection.cursor() as cursor:
        cursor.execute("UPDATE core_pessoa SET pais = NULL")


def noop(apps, schema_editor):
    """
    Função vazia para reverse.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_restructure_contacts"),
    ]

    operations = [
        # Primeiro limpa os dados de país
        migrations.RunPython(
            clear_pais_data,
            noop,
        ),
        # Depois altera o campo
        migrations.AlterField(
            model_name="pessoa",
            name="pais",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.pais",
                verbose_name="País",
            ),
        ),
    ]