# Generated by Django 5.2.4 on 2025-08-09 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_change_pais_to_foreignkey"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="telefone",
            name="pessoa",
        ),
        migrations.AddField(
            model_name="pessoa",
            name="ddd1",
            field=models.CharField(default="", max_length=3, verbose_name="DDD"),
        ),
        migrations.AddField(
            model_name="pessoa",
            name="ddd2",
            field=models.CharField(
                blank=True, max_length=3, null=True, verbose_name="DDD"
            ),
        ),
        migrations.AddField(
            model_name="pessoa",
            name="ddd3",
            field=models.CharField(
                blank=True, max_length=3, null=True, verbose_name="DDD"
            ),
        ),
        migrations.AddField(
            model_name="pessoa",
            name="ddi1",
            field=models.CharField(default="55", max_length=4, verbose_name="DDI"),
        ),
        migrations.AddField(
            model_name="pessoa",
            name="ddi2",
            field=models.CharField(
                blank=True, max_length=4, null=True, verbose_name="DDI"
            ),
        ),
        migrations.AddField(
            model_name="pessoa",
            name="ddi3",
            field=models.CharField(
                blank=True, max_length=4, null=True, verbose_name="DDI"
            ),
        ),
        migrations.AddField(
            model_name="pessoa",
            name="email1",
            field=models.EmailField(default="", max_length=254, verbose_name="Email"),
        ),
        migrations.AddField(
            model_name="pessoa",
            name="email2",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email"
            ),
        ),
        migrations.AddField(
            model_name="pessoa",
            name="email3",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email"
            ),
        ),
        migrations.AddField(
            model_name="pessoa",
            name="telefone1",
            field=models.CharField(default="", max_length=20, verbose_name="Telefone"),
        ),
        migrations.AddField(
            model_name="pessoa",
            name="telefone2",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Telefone"
            ),
        ),
        migrations.AddField(
            model_name="pessoa",
            name="telefone3",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Telefone"
            ),
        ),
        migrations.DeleteModel(
            name="Email",
        ),
        migrations.DeleteModel(
            name="Telefone",
        ),
    ]
