# Generated by Django 5.2.4 on 2025-08-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_update_pessoa_contacts"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="gerente_comercial",
            field=models.BooleanField(
                default=False,
                help_text="Usuário possui permissões gerenciais na área comercial",
                verbose_name="Gerente Comercial",
            ),
        ),
    ]
