# Generated by Django 5.2.4 on 2025-08-11 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_usuario_gerente_comercial"),
    ]

    operations = [
        migrations.AddField(
            model_name="whatsappconversation",
            name="data_retorno",
            field=models.DateField(
                blank=True,
                help_text="Data para retornar o contato com o cliente",
                null=True,
                verbose_name="Data de Retorno",
            ),
        ),
    ]
