# Generated by Django 5.2.5 on 2025-09-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_add_data_retorno_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappmessage',
            name='media_url',
            field=models.URLField(blank=True, max_length=2048, verbose_name='URL da Mídia'),
        ),
    ]
