# Generated by Django 5.2.4 on 2025-08-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_add_data_retorno_whatsapp"),
    ]

    operations = [
        migrations.AddField(
            model_name="caravana",
            name="repasse_moeda",
            field=models.CharField(
                choices=[("Dólar", "Dólar"), ("Real", "Real")],
                default="Dólar",
                max_length=10,
                verbose_name="Moeda do Repasse",
            ),
        ),
    ]
