# Generated by Django 5.2.5 on 2025-09-02 12:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_increase_media_url_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Unitário')),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desconto')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total')),
                ('extra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.extra', verbose_name='Extra')),
            ],
            options={
                'verbose_name': 'Extra da Venda',
                'verbose_name_plural': 'Extras da Venda',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='VendaBloqueio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Código da Venda')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('orcamento', 'Orçamento'), ('aguardando_pagamento', 'Aguardando Pagamento'), ('parcialmente_pago', 'Parcialmente Pago'), ('pago', 'Pago'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('concluida', 'Concluída')], default='rascunho', max_length=30, verbose_name='Status')),
                ('data_venda', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da Venda')),
                ('data_confirmacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Confirmação')),
                ('data_cancelamento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Cancelamento')),
                ('data_viagem', models.DateField(blank=True, null=True, verbose_name='Data da Viagem')),
                ('valor_passageiros', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Total Passageiros')),
                ('valor_extras', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Total Extras')),
                ('valor_seguro', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor do Seguro')),
                ('valor_taxas', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor de Taxas')),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desconto')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Total')),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Pago')),
                ('valor_pendente', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Pendente')),
                ('numero_passageiros', models.PositiveIntegerField(default=0, verbose_name='Número de Passageiros')),
                ('possui_seguro', models.BooleanField(default=False, verbose_name='Possui Seguro Viagem')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('observacoes_internas', models.TextField(blank=True, verbose_name='Observações Internas')),
                ('motivo_cancelamento', models.TextField(blank=True, verbose_name='Motivo do Cancelamento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('bloqueio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to='core.bloqueio', verbose_name='Bloqueio')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas_bloqueio_cliente', to='core.pessoa', verbose_name='Cliente')),
                ('extras', models.ManyToManyField(blank=True, related_name='vendas', through='core.ExtraVenda', to='core.extra', verbose_name='Extras')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas_bloqueio_vendedor', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Venda de Bloqueio',
                'verbose_name_plural': 'Vendas de Bloqueios',
                'ordering': ['-data_venda'],
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_pagamento', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('pix', 'PIX'), ('cartao_credito', 'Cartão de Crédito'), ('cartao_debito', 'Cartão de Débito'), ('boleto', 'Boleto'), ('transferencia', 'Transferência Bancária'), ('cheque', 'Cheque'), ('deposito', 'Depósito')], max_length=20, verbose_name='Forma de Pagamento')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('data_pagamento', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data do Pagamento')),
                ('data_confirmacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Confirmação')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado'), ('estornado', 'Estornado')], default='pendente', max_length=20, verbose_name='Status')),
                ('parcela', models.PositiveIntegerField(default=1, verbose_name='Parcela')),
                ('total_parcelas', models.PositiveIntegerField(default=1, verbose_name='Total de Parcelas')),
                ('referencia', models.CharField(blank=True, max_length=100, verbose_name='Referência/Comprovante')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='core.vendabloqueio', verbose_name='Venda')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-data_pagamento', 'parcela'],
            },
        ),
        migrations.AddField(
            model_name='extravenda',
            name='venda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vendabloqueio', verbose_name='Venda'),
        ),
        migrations.AddField(
            model_name='passageiro',
            name='venda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passageiros', to='core.vendabloqueio', verbose_name='Venda'),
        ),
        migrations.AddIndex(
            model_name='vendabloqueio',
            index=models.Index(fields=['codigo'], name='core_vendab_codigo_762a89_idx'),
        ),
        migrations.AddIndex(
            model_name='vendabloqueio',
            index=models.Index(fields=['status'], name='core_vendab_status_1147a1_idx'),
        ),
        migrations.AddIndex(
            model_name='vendabloqueio',
            index=models.Index(fields=['data_venda'], name='core_vendab_data_ve_20866a_idx'),
        ),
        migrations.AddIndex(
            model_name='vendabloqueio',
            index=models.Index(fields=['cliente'], name='core_vendab_cliente_a65265_idx'),
        ),
        migrations.AddIndex(
            model_name='vendabloqueio',
            index=models.Index(fields=['bloqueio'], name='core_vendab_bloquei_33e43e_idx'),
        ),
        migrations.AddIndex(
            model_name='pagamento',
            index=models.Index(fields=['venda', 'status'], name='core_pagame_venda_i_29e597_idx'),
        ),
        migrations.AddIndex(
            model_name='pagamento',
            index=models.Index(fields=['data_pagamento'], name='core_pagame_data_pa_e493e2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='extravenda',
            unique_together={('venda', 'extra')},
        ),
    ]
