# Generated by Django 5.2.5 on 2025-08-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_caravana_repasse_moeda'),
    ]

    operations = [
        migrations.AddField(
            model_name='caravana',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
