# Generated by Django 5.2.5 on 2025-08-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_caravana_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caravana',
            name='ativo',
            field=models.BooleanField(default=False, verbose_name='Ativo'),
        ),
    ]
