# Generated by Django 5.2.5 on 2025-09-03 14:59

from django.db import migrations


def atualizar_status_vendas(apps, schema_editor):
    """
    Atualiza os status das vendas para o novo padrão:
    - Todos os status antigos viram 'pre-venda'
    - Exceto 'confirmada', 'cancelada' e 'concluida' que se mantêm
    """
    VendaBloqueio = apps.get_model('core', 'VendaBloqueio')
    
    # Mapear status antigos para novos
    status_mapping = {
        'rascunho': 'pre-venda',
        'orcamento': 'pre-venda',
        'aguardando_pagamento': 'pre-venda',
        'parcialmente_pago': 'pre-venda',
        'pago': 'pre-venda',
        # 'confirmada' permanece 'confirmada'
        # 'cancelada' permanece 'cancelada'  
        # 'concluida' permanece 'concluida'
    }
    
    for old_status, new_status in status_mapping.items():
        VendaBloqueio.objects.filter(status=old_status).update(status=new_status)


def reverter_status_vendas(apps, schema_editor):
    """
    Reverte os status para o padrão anterior
    """
    VendaBloqueio = apps.get_model('core', 'VendaBloqueio')
    
    # Todas as pré-vendas voltam para rascunho
    VendaBloqueio.objects.filter(status='pre-venda').update(status='rascunho')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_extravenda_vendabloqueio_pagamento_extravenda_venda_and_more'),
    ]

    operations = [
        migrations.RunPython(atualizar_status_vendas, reverter_status_vendas),
    ]
