# Generated by Django 5.2.5 on 2025-08-22 20:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_caravana_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='caravana',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
