# Generated by Django 5.2.5 on 2025-09-03 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20250903_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendabloqueio',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendas_bloqueio_cliente', to='core.pessoa', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='vendabloqueio',
            name='status',
            field=models.CharField(choices=[('pre-venda', 'Pré-venda'), ('confirmada', 'Confirmada'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='rascunho', max_length=30, verbose_name='Status'),
        ),
    ]
