# Generated by Django 5.2.5 on 2025-08-25 12:32

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_caravana_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendaBloqueio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('em_andamento', 'Em Andamento'), ('aguardando_pagamento', 'Aguardando Pagamento'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='rascunho', max_length=30, verbose_name='Status')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('data_confirmacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Confirmação')),
                ('valor_produtos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Valor de Produtos')),
                ('valor_servicos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Valor de Serviços')),
                ('valor_extras', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Valor de Extras')),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Valor de Desconto')),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Valor Total')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('quantidade_passageiros', models.PositiveIntegerField(default=1, verbose_name='Quantidade de Passageiros')),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Valor Unitário')),
                ('bloqueio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to='core.bloqueio', verbose_name='Bloqueio')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_como_cliente', to='core.pessoa', verbose_name='Cliente')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Venda de Bloqueio',
                'verbose_name_plural': 'Vendas de Bloqueios',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
